name: E2E - Chart Install

on:
  pull_request:
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - feat/e2e

jobs:
  Install:
    name: Chart Install
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run E2E Test
        uses: ./.github/actions/e2e-tool
        with:
          e2e-file: $GITHUB_WORKSPACE/test/e2e/cases/chart-install/e2e.yaml
