name: E2E - Chart Install

on:
  pull_request:
    paths:
      - "**"
      - "!**.md"
  push:
    branches:
      - feat/e2e

jobs:
  Install:
    name: Chart Install
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build Docker images for Controller Manager
        uses: docker/build-push-action@v2.4.0
        with:
          file: config/dockerfiles/controller-manager/Dockerfile
          tags: kubespheredev/devops-controller:e2e
          push: false


      - name: Build Docker images for APIServer
        uses: docker/build-push-action@v2.4.0
        with:
          file: config/dockerfiles/apiserver/Dockerfile
          tags: kubespheredev/devops-apiserver:e2e
          push: false


      - name: Build Docker images for Tools
        uses: docker/build-push-action@v2.4.0
        with:
          file: config/dockerfiles/tools/Dockerfile
          tags: kubespheredev/devops-tools:e2e
          push: false

      - name: Run E2E Test
        uses: johnniang/skywalking-infra-e2e@main
        with:
          e2e-file: $GITHUB_WORKSPACE/test/e2e/cases/chart-install/e2e.yaml

      - name: Upload E2E Log
        uses: actions/upload-artifact@v2
        if: ${{ failure() }} # Only upload the artifact when E2E testing failure
        with:
          name: e2e-log
          path: "${{ env.SW_INFRA_E2E_LOG_DIR }}" # The SkyWalking Infra E2E action sets SW_INFRA_E2E_LOG_DIR automatically.
